#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

SORTABLE_VERSION    = '1.0.0'
SORTABLE_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
SORTABLE_BUILD_NAME = 'right-sortable'

SORTABLE_FILES = %w{
  sortable
  document
  element
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Autocompleter\n"
  
  FileUtils.mkdir_p SORTABLE_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = SORTABLE_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
#  @source << "\n\n#{@compiler.inline_css(File.open('autocompleter.css').read)}"
  
  @source.gsub! '#{version}', SORTABLE_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{SORTABLE_BUILD_DIR}/#{SORTABLE_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end