#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

RATER_VERSION    = '1.0.0'
RATER_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
RATER_BUILD_NAME = 'right-rater'

RATER_FILES = %w{
  rater
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Rater\n"
  
  FileUtils.mkdir_p RATER_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = RATER_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('rater.css').read)}"
  
  @source.gsub! '#{version}', RATER_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{RATER_BUILD_DIR}/#{RATER_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end