#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

LIGHTBOX_VERSION    = '1.0.0'
LIGHTBOX_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
LIGHTBOX_BUILD_NAME = 'right-lightbox'

LIGHTBOX_FILES = %w{
  lightbox
  lightbox/loader
  lightbox/roadtrip
  lightbox/image
  lightbox/static
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Lightbox\n"
  
  FileUtils.mkdir_p LIGHTBOX_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = LIGHTBOX_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('lightbox.css').read)}"
  
  @source.gsub! '#{version}', LIGHTBOX_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{LIGHTBOX_BUILD_DIR}/#{LIGHTBOX_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end