#
# The module building tool
#
# Copyright (C) 2010 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

UPLOADER_VERSION    = '1.0.0'
UPLOADER_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
UPLOADER_BUILD_NAME = 'right-uploader'

UPLOADER_FILES = %w{
  uploader
  form
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Uploader\n"
  
  FileUtils.mkdir_p UPLOADER_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = UPLOADER_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('uploader.css').read)}"
  
  @source.gsub! '#{version}', UPLOADER_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{UPLOADER_BUILD_DIR}/#{UPLOADER_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end