#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

TABS_VERSION    = '1.0.0'
TABS_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
TABS_BUILD_NAME = 'right-tabs'

TABS_FILES = %w{
  tabs
  tabs/tab
  tabs/panel
  tabs/scroll
  tabs/current
  tabs/builder
  tabs/remote
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Tabs\n"
  
  FileUtils.mkdir_p TABS_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = TABS_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('tabs.css').read)}"
  
  @source.gsub! '#{version}', TABS_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{TABS_BUILD_DIR}/#{TABS_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end