#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

SELECTABLE_VERSION    = '1.0.0'
SELECTABLE_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
SELECTABLE_BUILD_NAME = 'right-selectable'

SELECTABLE_FILES = %w{
  selectable
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Selectable\n"
  
  FileUtils.mkdir_p SELECTABLE_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = SELECTABLE_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('selectable.css').read)}"
  
  @source.gsub! '#{version}', SELECTABLE_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{SELECTABLE_BUILD_DIR}/#{SELECTABLE_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end