#
# The module building tool
#
# Copyright (C) 2009 Nikolay V. Nemshilov aka St.
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

CALENDAR_VERSION    = '1.0.0'
CALENDAR_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
CALENDAR_BUILD_NAME = 'right-calendar'

CALENDAR_FILES = %w{
  calendar
  calendar/builder
  calendar/events
  calendar/assign
  calendar/formats
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Calendar\n"
  
  FileUtils.mkdir_p CALENDAR_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = CALENDAR_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('calendar.css').read)}"
  
  @source.gsub! '#{version}', CALENDAR_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{CALENDAR_BUILD_DIR}/#{CALENDAR_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end