#
# The module building tool
#
# Copyright (C) 2009-2010 Nikolay V. Nemshilov
#

require 'rake'
require 'fileutils'
require File.dirname(__FILE__) + "/../../lib/frontcompiler/init.rb"

AUTOCOMPLETER_VERSION    = '1.0.0'
AUTOCOMPLETER_BUILD_DIR  = File.dirname(__FILE__) + "/../../build"
AUTOCOMPLETER_BUILD_NAME = 'right-autocompleter'

AUTOCOMPLETER_FILES = %w{
  autocompleter
  document
}

task :default => :build

desc "Builds the module"
task :build do
  puts "\n * Building Autocompleter\n"
  
  FileUtils.mkdir_p AUTOCOMPLETER_BUILD_DIR
  
  # removing the old versions
  FileUtils.rm "#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}.js"     rescue nil
  FileUtils.rm "#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}-min.js" rescue nil
  FileUtils.rm "#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}-src.js" rescue nil
  
  @compiler = FrontCompiler.new
  
  @source   = AUTOCOMPLETER_FILES.collect do |filename|
    File.open("#{filename}.js").read
  end.join("\n\n")
  
  @source << "\n\n#{@compiler.inline_css(File.open('autocompleter.css').read)}"
  
  @source.gsub! '#{version}', AUTOCOMPLETER_VERSION
  
  @header   = File.open("header.js").read
  
  # writting files
  File.open("#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source).create_self_build
  end
  
  File.open("#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}-min.js", "w") do |file|
    file.write @header
    file.write @compiler.compact_js(@source)
  end
  
  File.open("#{AUTOCOMPLETER_BUILD_DIR}/#{AUTOCOMPLETER_BUILD_NAME}-src.js", "w") do |file|
    file.write @header
    file.write "\n#{@source}"
  end
end